apiVersion: apps/v1
kind: Deployment
metadata:
  name: capture-criminal-tg-bot
  namespace: {{ .Release.Namespace }}
  labels:
    app: capture-criminal-tg-bot
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: 'capture-criminal-tg-bot'
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capture-criminal-tg-bot
    spec:
      containers:
      - name: main
        image: "{{ $.Values.image.image }}:{{ $.Values.image.tag }}"
        imagePullPolicy: Always
        command: ["/app/app"]
        args:
        - "-config=/etc/capture-criminal-tg-bot/config.yaml"
        volumeMounts:
        - name: config
          mountPath: /etc/capture-criminal-tg-bot
      volumes:
      - name: config
        configMap:
          name: capture-criminal-tg-bot